name: Jira Version Action
description: A GitHub action to create Jira versions
inputs:
  email:
    required: true
    description: Email address associated with api token
  api_token:
    required: true
    description: Jira api token
  host:
    required: true
    description: Jira project host
  project_key:
    required: true
    description: Project key
  version:
    required: true
    description: Name of the version
  release:
    type: boolean
    required: false
    description: Release the version
    default: false
  delete:
    type: boolean
    required: false
    description: Delete the version
    default: false

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Script
      shell: bash
      run: |
        python ${{ github.action_path }}/jira.py \
          --email='${{ inputs.email }}' \
          --api_token='${{ inputs.api_token }}' \
          --project_key='${{ inputs.project_key }}' \
          --host='${{ inputs.host }}' \
          --version='${{ inputs.version }}' \
          ${{ inputs.release == 'true' && '--release' || '' }} \
          ${{ inputs.delete == 'true' && '--delete' || '' }}
